export const CONFIG = Object.freeze({
  APP_NAME: 'SYNAPSE',
  APP_TAGLINE_FA: 'مرجع هوشمند کتابخانه‌های برنامه‌نویسی',
  APP_TAGLINE_EN: 'Smart Library Reference for Developers',
  VERSION: '1.0.0',
  BUILD_DATE: '2026-07-15',
  AUTHOR: 'Mohammad Javad Ghaderi',
  AUTHOR_FA: 'محمد جواد قادری',
  REPOSITORY: 'https://github.com/mjghaderi/synapse',

  SPLASH_DURATION: 2800,
  SPLASH_MIN_DISPLAY: 1800,
  SPLASH_SKIP_ON_REVISIT: true,
  SPLASH_SKIP_KEY: 'synapse_splash_seen',
  SPLASH_PARTICLE_COUNT_LOW: 30,
  SPLASH_PARTICLE_COUNT_HIGH: 80,
  SPLASH_PARTICLE_CONNECTION_DIST: 120,

  DEBOUNCE_AUTOCOMPLETE: 150,
  DEBOUNCE_SEARCH: 300,
  THINKING_MIN_DURATION: 600,
  THINKING_MAX_DURATION: 2500,
  THINKING_RANDOM_EXTRA: 400,
  MAX_AUTOCOMPLETE_RESULTS: 5,
  MAX_SEARCH_RESULTS: 12,
  MAX_CHAT_HISTORY_MESSAGES: 200,
  FUZZY_THRESHOLD: 0.08,
  SEMANTIC_THRESHOLD: 0.03,
  RRF_K: 60,
  FUZZY_WEIGHT: 1.0,
  SEMANTIC_WEIGHT: 0.8,
  JACCARD_WEIGHT: 0.5,
  NAME_MATCH_EXACT: 0.3,
  NAME_MATCH_ALIAS: 0.25,
  TAG_MATCH_BONUS: 0.2,
  AUTOCMOPLETE_NAME_STARTS: 10,
  AUTOCOMPLETE_NAME_CONTAINS: 5,
  AUTOCOMPLETE_FA_NAME: 8,
  AUTOCOMPLETE_ALIAS_STARTS: 6,
  AUTOCOMPLETE_ALIAS_CONTAINS: 3,
  AUTOCOMPLETE_TAG: 3,
  AUTOCOMPLETE_CATEGORY: 2,

  AI_MODEL_NAME: 'Xenova/all-MiniLM-L6-v2',
  AI_MODEL_DIMENSIONS: 384,
  AI_MODEL_SIZE_MB: 23,
  AI_LAZY_LOAD: true,
  AI_CACHE_IN_INDEXEDDB: true,
  AI_FALLBACK_TO_FUZZY: true,

  DB_NAME: 'synapse_db',
  DB_VERSION: 1,
  MAX_CONVERSATIONS: 100,
  MAX_SUGGESTIONS_PER_DAY: 3,
  MAX_IMPORT_SIZE_BYTES: 10485760,
  STORAGE_WARNING_PERCENT: 80,
  PREFERENCES_KEY: 'synapse_preferences',
  SUGGESTIONS_KEY: 'synapse_suggestions',
  TOUR_SEEN_KEY: 'synapse_tour_seen',
  LAST_SESSION_KEY: 'synapse_last_session',
  ADMIN_HASH: 'devtools',
  SEARCH_HISTORY_LIMIT: 200,

  FEATURES: Object.freeze({
    ENABLE_VECTOR_SEARCH: true,
    ENABLE_FUZZY_SEARCH: true,
    ENABLE_INTENT_DETECTION: true,
    ENABLE_COMMAND_PALETTE: true,
    ENABLE_SPLASH_SCREEN: true,
    ENABLE_TOUR_GUIDE: false,
    ENABLE_VOICE_INPUT: false,
    ENABLE_LIVE_PLAYGROUND: false,
    ENABLE_COMPARISON_MODE: false,
    ENABLE_COLLECTIONS: false,
    DEBUG_MODE: false
  }),

  TARGET_FCP_MS: 800,
  TARGET_LCP_MS: 1500,
  TARGET_TTI_MS: 2500,
  TARGET_CLS: 0.1,
  TARGET_FPS: 60,

  CDN: Object.freeze({
    TAILWIND: 'https://cdn.tailwindcss.com',
    LUCIDE: 'https://unpkg.com/lucide@latest',
    TRANSFORMERS: 'https://cdn.jsdelivr.net/npm/@xenova/transformers',
    FUSE_JS: 'https://cdn.jsdelivr.net/npm/fuse.js',
    VECTRA: 'https://cdn.jsdelivr.net/npm/vectra',
    MARKED: 'https://cdn.jsdelivr.net/npm/marked',
    DOMPURIFY: 'https://cdn.jsdelivr.net/npm/dompurify',
    SHIKI: 'https://cdn.jsdelivr.net/npm/shiki',
    HUGGINGFACE: 'https://huggingface.co'
  })
});

export const ENV = (function() {
  var ua = navigator.userAgent;
  var width = window.innerWidth;
  var height = window.innerHeight;
  var isMobileUA = /Android|iPhone|iPad|iPod|webOS|BlackBerry|IEMobile|Opera Mini/i.test(ua);
  var isTabletUA = /iPad|Android(?!.*Mobile)/i.test(ua) || (isMobileUA && width >= 768);
  var isDesktopUA = !isMobileUA && !isTabletUA;
  var isMobile = width < 768;
  var isTablet = width >= 768 && width < 1024;
  var isDesktop = width >= 1024;
  var isChrome = /Chrome/.test(ua) && !/Edge|OPR|Brave/.test(ua);
  var isFirefox = /Firefox/.test(ua);
  var isSafari = /Safari/.test(ua) && !/Chrome/.test(ua);
  var isEdge = /Edg/.test(ua);
  var isBrave = /Brave/.test(ua);

  var supportsWasm = typeof WebAssembly !== 'undefined';
  var supportsServiceWorker = 'serviceWorker' in navigator;
  var supportsIndexedDB = 'indexedDB' in window;

  var supportsLocalStorage = false;
  try { localStorage.setItem('__t__', '1'); localStorage.removeItem('__t__'); supportsLocalStorage = true; }
  catch(e) { supportsLocalStorage = false; }

  var hardwareConcurrency = navigator.hardwareConcurrency || 4;
  var deviceMemory = navigator.deviceMemory || 4;
  var isLowEndDevice = hardwareConcurrency <= 2 || deviceMemory <= 2;
  var isHighEndDevice = hardwareConcurrency >= 8 && deviceMemory >= 8;

  var conn = navigator.connection || navigator.mozConnection || navigator.webkitConnection;
  var connection = {
    type: conn ? (conn.type || 'unknown') : 'unknown',
    effectiveType: conn ? (conn.effectiveType || '4g') : '4g',
    downlink: conn ? (conn.downlink || 10) : 10,
    rtt: conn ? (conn.rtt || 50) : 50,
    saveData: conn ? (conn.saveData || false) : false
  };
  var isSlowConnection = connection.effectiveType === 'slow-2g' || connection.effectiveType === '2g';
  var isDataSaver = connection.saveData;

  var prefersDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;
  var prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var prefersHighContrast = window.matchMedia('(prefers-contrast: high)').matches;
  var prefersRTL = navigator.language.startsWith('fa') || navigator.language.startsWith('ar');

  var pixelRatio = window.devicePixelRatio || 1;
  var isRetina = pixelRatio >= 2;
  var viewportWidth = width;
  var viewportHeight = height;

  var isOnline = navigator.onLine;

  return Object.freeze({
    isMobileUA: isMobileUA,
    isTabletUA: isTabletUA,
    isDesktopUA: isDesktopUA,
    isMobile: isMobile,
    isTablet: isTablet,
    isDesktop: isDesktop,
    isChrome: isChrome,
    isFirefox: isFirefox,
    isSafari: isSafari,
    isEdge: isEdge,
    isBrave: isBrave,
    supportsWasm: supportsWasm,
    supportsServiceWorker: supportsServiceWorker,
    supportsIndexedDB: supportsIndexedDB,
    supportsLocalStorage: supportsLocalStorage,
    hardwareConcurrency: hardwareConcurrency,
    deviceMemory: deviceMemory,
    isLowEndDevice: isLowEndDevice,
    isHighEndDevice: isHighEndDevice,
    connection: connection,
    isSlowConnection: isSlowConnection,
    isDataSaver: isDataSaver,
    prefersDarkMode: prefersDarkMode,
    prefersReducedMotion: prefersReducedMotion,
    prefersHighContrast: prefersHighContrast,
    prefersRTL: prefersRTL,
    pixelRatio: pixelRatio,
    isRetina: isRetina,
    viewportWidth: viewportWidth,
    viewportHeight: viewportHeight,
    isOnline: isOnline,
    supportsWebGL: function() {
      try {
        var canvas = document.createElement('canvas');
        return !!(canvas.getContext('webgl') || canvas.getContext('experimental-webgl'));
      } catch(e) { return false; }
    },
    isPrivateMode: function() {
      return new Promise(function(resolve) {
        try { var k = '__synapse_pvt__'; localStorage.setItem(k, '1'); localStorage.removeItem(k); resolve(false); }
        catch(e) { resolve(true); }
      });
    }
  });
})();

export const THEMES = Object.freeze({
  dark: {
    bg: { base: '#0A0A0F', elevated: '#13131A', surface: '#1A1A24', overlay: 'rgba(0,0,0,0.75)' },
    border: { subtle: '#1F1F2E', default: '#2A2A3A', strong: '#3F3F52' },
    text: { primary: '#E4E4E7', secondary: '#A1A1AA', muted: '#71717A', disabled: '#52525B', inverse: '#0A0A0F' },
    brand: {
      violet: { 400: '#A78BFA', 500: '#8B5CF6', 600: '#7C3AED' },
      cyan: { 400: '#22D3EE', 500: '#06B6D4', 600: '#0891B2' },
      pink: { 400: '#F472B6', 500: '#EC4899' }
    },
    semantic: { success: '#10B981', successBg: '#022C22', warning: '#F59E0B', warningBg: '#2C1F00', error: '#F43F5E', errorBg: '#2C0006', info: '#3B82F6', infoBg: '#001F3F' },
    gradient: {
      aurora: 'linear-gradient(135deg, #8B5CF6 0%, #06B6D4 50%, #EC4899 100%)',
      auroraSubtle: 'linear-gradient(135deg, rgba(139,92,246,0.08) 0%, rgba(6,182,212,0.08) 100%)',
      text: 'linear-gradient(90deg, #A78BFA 0%, #22D3EE 100%)'
    },
    shadow: {
      sm: '0 1px 2px rgba(0,0,0,0.3)',
      md: '0 4px 6px -1px rgba(0,0,0,0.4)',
      lg: '0 10px 15px -3px rgba(0,0,0,0.4)',
      xl: '0 20px 25px -5px rgba(0,0,0,0.5)',
      glowViolet: '0 0 20px rgba(139,92,246,0.35)',
      glowCyan: '0 0 20px rgba(6,182,212,0.35)'
    }
  },
  light: {
    bg: { base: '#FAFAFA', elevated: '#FFFFFF', surface: '#F4F4F5', overlay: 'rgba(0,0,0,0.5)' },
    border: { subtle: '#E4E4E7', default: '#D4D4D8', strong: '#A1A1AA' },
    text: { primary: '#18181B', secondary: '#52525B', muted: '#71717A', disabled: '#A1A1AA', inverse: '#FAFAFA' },
    brand: {
      violet: { 400: '#A78BFA', 500: '#8B5CF6', 600: '#7C3AED' },
      cyan: { 400: '#22D3EE', 500: '#06B6D4', 600: '#0891B2' },
      pink: { 400: '#F472B6', 500: '#EC4899' }
    },
    semantic: { success: '#059669', successBg: '#ECFDF5', warning: '#D97706', warningBg: '#FFFBEB', error: '#DC2626', errorBg: '#FEF2F2', info: '#2563EB', infoBg: '#EFF6FF' },
    gradient: {
      aurora: 'linear-gradient(135deg, #8B5CF6 0%, #06B6D4 50%, #EC4899 100%)',
      auroraSubtle: 'linear-gradient(135deg, rgba(139,92,246,0.06) 0%, rgba(6,182,212,0.06) 100%)',
      text: 'linear-gradient(90deg, #7C3AED 0%, #0891B2 100%)'
    },
    shadow: {
      sm: '0 1px 2px rgba(0,0,0,0.05)',
      md: '0 4px 6px -1px rgba(0,0,0,0.08)',
      lg: '0 10px 15px -3px rgba(0,0,0,0.08)',
      xl: '0 20px 25px -5px rgba(0,0,0,0.1)',
      glowViolet: '0 0 20px rgba(139,92,246,0.25)',
      glowCyan: '0 0 20px rgba(6,182,212,0.25)'
    }
  }
});

export const I18N = Object.freeze({
  fa: {
    'app.name': 'SYNAPSE',
    'app.tagline': 'مرجع هوشمند کتابخانه‌های برنامه‌نویسی',
    'app.version': 'نسخه',
    'app.loading': 'در حال بارگذاری...',
    'app.offline': 'شما آفلاین هستید. برخی ویژگی‌ها محدود است.',
    'nav.chat': 'چت',
    'nav.history': 'تاریخچه',
    'nav.about': 'درباره ما',
    'nav.settings': 'تنظیمات',
    'nav.suggest': 'پیشنهاد کتابخانه',
    'splash.initializing': 'در حال راه‌اندازی هسته SYNAPSE...',
    'splash.loading_model': 'بارگذاری مدل هوش مصنوعی...',
    'splash.ready': 'آماده!',
    'chat.welcome_title': '👋 سلام! من SYNAPSE هستم',
    'chat.welcome_text': 'دستیار هوشمند مرجع کتابخانه‌های برنامه‌نویسی.\n\nمی‌تونم کمکت کنم:\n• 🔍 کتابخانه مناسب پروژه‌ات رو پیدا کنی\n• ⚖️ جایگزین‌ها رو مقایسه کنی\n• 💻 نمونه کد و Best Practices ببینی\n• 📦 لینک نصب و مستندات دریافت کنی\n\n**چطور می‌تونم کمکت کنم؟**\n\n💡 *نکته: با `Cmd+K` می‌تونی سریع‌تر جستجو کنی*',
    'chat.input_placeholder': 'نام کتابخانه یا توضیح آن را بنویسید...',
    'chat.send': 'ارسال',
    'chat.thinking': 'در حال تحلیل...',
    'chat.you': 'شما',
    'chat.assistant': 'SYNAPSE',
    'search.found_single': 'بر اساس جستجوی شما، این کتابخانه رو پیدا کردم:',
    'search.found_multiple': 'بر اساس جستجوی **«{query}»**، **{count}** کتابخانه مرتبط پیدا کردم:',
    'search.found_here': 'ایناهاش 👇',
    'search.no_results': 'متأسفانه برای **«{query}»** نتیجه‌ای پیدا نکردم. 😕\n\nپیشنهاد می‌کنم این‌ها رو امتحان کنی:',
    'search.typo_hint': 'شاید منظور شما **«{corrected}»** بوده؟',
    'search.showing_top': 'نمایش {shown} نتیجه برتر از {total}:',
    'library.intro': '📚 **{name}** — {description}',
    'library.external_notice': 'این یک کتابخانه **خارجی (Third-Party)** است و توسط SYNAPSE نگهداری نمی‌شود.',
    'library.install': '📦 **نصب**',
    'library.docs': 'مستندات',
    'library.github': 'گیت‌هاب',
    'library.npm': 'npm',
    'library.use_cases': '🎯 **موارد استفاده:**',
    'library.pros': '✅ **مزایا:**',
    'library.cons': '⚠️ **محدودیت‌ها:**',
    'library.alternatives': '⚖️ **جایگزین‌ها:**',
    'library.metrics': '📊 **آمار:**',
    'library.stars': 'ستاره',
    'library.downloads': 'دانلود هفتگی',
    'library.bundle_size': 'حجم باندل',
    'library.license': 'مجوز',
    'library.updated': 'آخرین به‌روزرسانی',
    'library.code_example': '💻 **نمونه کد:**',
    'library.copy_code': 'کپی کد',
    'library.copied': 'کد کپی شد! ✅',
    'library.copy_install': 'کپی دستور نصب',
    'library.install_copied': 'دستور نصب کپی شد! ✅',
    'library.open_link': 'باز کردن لینک',
    'library.more_details': 'اطلاعات بیشتر',
    'action.search': 'جستجو',
    'action.compare': 'مقایسه',
    'action.learn': 'یادگیری',
    'action.suggest': 'پیشنهاد',
    'action.share': 'اشتراک‌گذاری',
    'action.copy': 'کپی',
    'action.export': 'خروجی',
    'action.import': 'ورودی',
    'action.delete': 'حذف',
    'action.clear': 'پاک کردن',
    'action.retry': 'تلاش مجدد',
    'action.refresh': 'بارگذاری مجدد',
    'history.title': '📜 تاریخچه گفتگوها',
    'history.empty': 'هنوز گفتگویی ثبت نشده.',
    'history.empty_cta': 'شروع اولین گفتگو',
    'history.search': 'جستجو در تاریخچه...',
    'history.delete_confirm': 'آیا از حذف این گفتگو مطمئن هستید؟',
    'history.continue': 'ادامه گفتگو',
    'history.messages_count': '{count} پیام',
    'history.today': 'امروز',
    'history.yesterday': 'دیروز',
    'history.days_ago': '{n} روز پیش',
    'history.clear_all': 'پاک کردن همه',
    'about.title': 'درباره SYNAPSE',
    'about.founder': 'محمد جواد قادری',
    'about.founder_title': 'بنیان‌گذار و معمار ارشد',
    'about.bio': 'توسعه‌دهنده Full-Stack با تمرکز بر معماری‌های مدرن وب و هوش مصنوعی.',
    'about.stats_libraries': 'کتابخانه',
    'about.stats_categories': 'دسته‌بندی',
    'about.stats_searches': 'جستجوی کل',
    'about.stats_uptime': 'آپتایم',
    'about.tech_stack': '🛠️ تکنولوژی‌ها',
    'about.mission': '🎯 مأموریت',
    'about.mission_text': 'حذف «اصطکاک ذهنی» در کشف و یادگیری ابزارهای توسعه.',
    'about.privacy': '🔒 حریم خصوصی',
    'about.privacy_text': 'SYNAPSE هیچ داده‌ای را جمع‌آوری یا ارسال نمی‌کند. تمام پردازش‌ها در مرورگر شما انجام می‌شود.',
    'about.open_source': '📖 متن‌باز',
    'about.open_source_text': 'SYNAPSE یک پروژه Open-Source تحت مجوز MIT است.',
    'suggest.title': 'پیشنهاد کتابخانه جدید',
    'suggest.name': 'نام کتابخانه',
    'suggest.url': 'لینک (GitHub یا مستندات)',
    'suggest.reason': 'چرا این کتابخانه مفید است؟',
    'suggest.submit': 'ارسال پیشنهاد',
    'suggest.remaining': '{count} پیشنهاد باقی‌مانده از {max}',
    'suggest.remaining_zero': 'سهمیه امروز تمام شد. فردا دوباره امتحان کنید.',
    'suggest.success': '🎉 ممنون از مشارکت شما!',
    'suggest.success_detail': 'پیشنهاد شما ثبت شد و در آپدیت بعدی بررسی می‌شود.',
    'suggest.error': 'خطا در ثبت پیشنهاد. دوباره تلاش کنید.',
    'settings.title': 'تنظیمات',
    'settings.appearance': 'ظاهر',
    'settings.theme': 'تم',
    'settings.theme_dark': 'تاریک',
    'settings.theme_light': 'روشن',
    'settings.theme_auto': 'خودکار',
    'settings.language': 'زبان',
    'settings.language_fa': 'فارسی',
    'settings.language_en': 'English',
    'settings.font_size': 'اندازه فونت',
    'settings.font_small': 'کوچک',
    'settings.font_medium': 'متوسط',
    'settings.font_large': 'بزرگ',
    'settings.reduced_motion': 'کاهش انیمیشن‌ها',
    'settings.high_contrast': 'کنتراست بالا',
    'settings.search': 'جستجو',
    'settings.max_results': 'حداکثر نتایج',
    'settings.auto_suggest': 'پیشنهاد خودکار',
    'settings.chat': 'چت',
    'settings.auto_scroll': 'اسکرول خودکار',
    'settings.compact_mode': 'حالت فشرده',
    'settings.data': 'داده‌ها',
    'settings.export_data': 'خروجی گرفتن از داده‌ها',
    'settings.import_data': 'ورودی داده‌ها',
    'settings.clear_data': 'پاک کردن همه داده‌ها',
    'settings.clear_confirm': 'آیا از پاک کردن تمام داده‌ها مطمئن هستید؟ این عملیات قابل بازگشت نیست.',
    'settings.saved': 'تنظیمات ذخیره شد',
    'command.placeholder': 'یک دستور یا جستجو تایپ کنید...',
    'command.libraries': 'کتابخانه‌ها',
    'command.actions': 'عملیات',
    'command.settings_cmd': 'تنظیمات',
    'command.theme_toggle': 'تغییر تم',
    'command.lang_toggle': 'تغییر زبان',
    'command.history_open': 'تاریخچه',
    'command.about_open': 'درباره ما',
    'command.suggest_lib': 'پیشنهاد کتابخانه',
    'command.export_data': 'خروجی داده‌ها',
    'command.navigate': '↑↓ پیمایش',
    'command.select': '↵ انتخاب',
    'command.close': 'Esc بستن',
    'tour.welcome': 'به SYNAPSE خوش آمدید! 🎉',
    'tour.welcome_text': 'بگذارید یک تور سریع بهت بدم...',
    'tour.search': 'اینجا می‌تونی هر کتابخانه‌ای رو جستجو کنی',
    'tour.command': 'با Cmd+K سریع‌تر به همه‌چیز دسترسی داری',
    'tour.history': 'گفتگوهای قبلیت اینجا ذخیره می‌شن',
    'tour.done': 'حالا آماده‌ای! 🚀',
    'toast.code_copied': 'کد کپی شد!',
    'toast.link_copied': 'لینک کپی شد!',
    'toast.install_copied': 'دستور نصب کپی شد!',
    'toast.settings_saved': 'تنظیمات ذخیره شد.',
    'toast.export_success': 'داده‌ها با موفقیت خروجی گرفته شد.',
    'toast.import_success': 'داده‌ها با موفقیت وارد شد.',
    'toast.data_cleared': 'همه داده‌ها پاک شد.',
    'toast.conversation_deleted': 'گفتگو حذف شد.',
    'toast.error_generic': 'خطایی رخ داد. لطفاً دوباره تلاش کنید.',
    'toast.clipboard_denied': 'دسترسی به کلیپ‌بورد ممکن نیست. لطفاً دستی کپی کنید.',
    'error.network': '🌐 مشکل در اتصال اینترنت. لطفاً اتصال خود را بررسی کنید.',
    'error.ai_load': '🧠 بارگذاری هوش مصنوعی ناموفق بود. از جستجوی ساده استفاده می‌شود.',
    'error.data_load': '📂 بارگذاری داده‌ها ناموفق بود.',
    'error.storage_full': '💾 فضای ذخیره‌سازی پر است. برخی ویژگی‌ها محدود شد.',
    'error.import_invalid': '📥 فایل ورودی نامعتبر است.',
    'error.import_too_large': '📥 حجم فایل بیش از حد مجاز است.',
    'error.unknown': '⚠️ خطای غیرمنتظره. لطفاً صفحه را مجدداً بارگذاری کنید.',
    'common.ok': 'باشه',
    'common.cancel': 'انصراف',
    'common.save': 'ذخیره',
    'common.delete': 'حذف',
    'common.edit': 'ویرایش',
    'common.close': 'بستن',
    'common.back': 'بازگشت',
    'common.next': 'بعدی',
    'common.previous': 'قبلی',
    'common.loading': 'در حال بارگذاری...',
    'common.error': 'خطا',
    'common.success': 'موفق',
    'common.warning': 'هشدار',
    'common.info': 'اطلاعات',
    'common.search': 'جستجو...',
    'common.no_results': 'نتیجه‌ای یافت نشد',
    'common.all': 'همه',
    'common.none': 'هیچ',
    'common.optional': 'اختیاری',
    'common.required': 'الزامی',
    'shortcuts.title': 'میانبرهای کیبورد',
    'shortcuts.search': 'جستجوی سریع',
    'shortcuts.theme': 'تغییر تم',
    'shortcuts.language': 'تغییر زبان',
    'shortcuts.new_chat': 'گفتگوی جدید',
    'shortcuts.history': 'تاریخچه',
    'shortcuts.close': 'بستن',
    'shortcuts.send': 'ارسال پیام',
    'shortcuts.focus_input': 'فوکوس روی ورودی',
    'devtools.title': 'ابزارهای توسعه‌دهنده',
    'devtools.suggestions': 'پیشنهادات کاربران',
    'devtools.no_suggestions': 'هیچ پیشنهادی ثبت نشده.',
    'devtools.generate_issue': 'تولید GitHub Issue',
    'devtools.issue_generated': 'Issue آماده شد. لینک کپی شد.',
    'devtools.export_suggestions': 'خروجی پیشنهادات'
  },
  en: {
    'app.name': 'SYNAPSE',
    'app.tagline': 'Smart Library Reference for Developers',
    'app.version': 'Version',
    'app.loading': 'Loading...',
    'app.offline': 'You are offline. Some features are limited.',
    'nav.chat': 'Chat',
    'nav.history': 'History',
    'nav.about': 'About',
    'nav.settings': 'Settings',
    'nav.suggest': 'Suggest Library',
    'splash.initializing': 'Initializing SYNAPSE Core...',
    'splash.loading_model': 'Loading AI model...',
    'splash.ready': 'Ready!',
    'chat.welcome_title': '👋 Hi! I\'m SYNAPSE',
    'chat.welcome_text': 'Your intelligent library reference assistant.\n\nI can help you:\n• 🔍 Find the right library for your project\n• ⚖️ Compare alternatives\n• 💻 See code examples & best practices\n• 📦 Get install links & documentation\n\n**How can I help you today?**\n\n💡 *Tip: Press `Cmd+K` for quick search*',
    'chat.input_placeholder': 'Type a library name or description...',
    'chat.send': 'Send',
    'chat.thinking': 'Analyzing...',
    'chat.you': 'You',
    'chat.assistant': 'SYNAPSE',
    'search.found_single': 'Based on your search, here\'s the library I found:',
    'search.found_multiple': 'Based on **"{query}"**, I found **{count}** related libraries:',
    'search.found_here': 'Here you go 👇',
    'search.no_results': 'Sorry, I couldn\'t find anything for **"{query}"**. 😕\n\nTry these suggestions:',
    'search.typo_hint': 'Did you mean **"{corrected}"**?',
    'search.showing_top': 'Showing top {shown} of {total}:',
    'library.intro': '📚 **{name}** — {description}',
    'library.external_notice': 'This is a **third-party library** and is not maintained by SYNAPSE.',
    'library.install': '📦 **Install**',
    'library.docs': 'Documentation',
    'library.github': 'GitHub',
    'library.npm': 'npm',
    'library.use_cases': '🎯 **Use Cases:**',
    'library.pros': '✅ **Pros:**',
    'library.cons': '⚠️ **Cons:**',
    'library.alternatives': '⚖️ **Alternatives:**',
    'library.metrics': '📊 **Metrics:**',
    'library.stars': 'stars',
    'library.downloads': 'weekly downloads',
    'library.bundle_size': 'bundle size',
    'library.license': 'license',
    'library.updated': 'last updated',
    'library.code_example': '💻 **Code Example:**',
    'library.copy_code': 'Copy code',
    'library.copied': 'Code copied! ✅',
    'library.copy_install': 'Copy install command',
    'library.install_copied': 'Install command copied! ✅',
    'library.open_link': 'Open link',
    'library.more_details': 'More details',
    'action.search': 'Search',
    'action.compare': 'Compare',
    'action.learn': 'Learn',
    'action.suggest': 'Suggest',
    'action.share': 'Share',
    'action.copy': 'Copy',
    'action.export': 'Export',
    'action.import': 'Import',
    'action.delete': 'Delete',
    'action.clear': 'Clear',
    'action.retry': 'Retry',
    'action.refresh': 'Refresh',
    'history.title': '📜 Conversation History',
    'history.empty': 'No conversations yet.',
    'history.empty_cta': 'Start your first conversation',
    'history.search': 'Search history...',
    'history.delete_confirm': 'Are you sure you want to delete this conversation?',
    'history.continue': 'Continue conversation',
    'history.messages_count': '{count} messages',
    'history.today': 'Today',
    'history.yesterday': 'Yesterday',
    'history.days_ago': '{n} days ago',
    'history.clear_all': 'Clear all',
    'about.title': 'About SYNAPSE',
    'about.founder': 'Mohammad Javad Ghaderi',
    'about.founder_title': 'Founder & Chief Architect',
    'about.bio': 'Full-Stack Developer focused on modern web architectures and AI.',
    'about.stats_libraries': 'libraries',
    'about.stats_categories': 'categories',
    'about.stats_searches': 'total searches',
    'about.stats_uptime': 'uptime',
    'about.tech_stack': '🛠️ Tech Stack',
    'about.mission': '🎯 Mission',
    'about.mission_text': 'Eliminate "mental friction" in discovering and learning development tools.',
    'about.privacy': '🔒 Privacy',
    'about.privacy_text': 'SYNAPSE collects zero data. All processing happens in your browser.',
    'about.open_source': '📖 Open Source',
    'about.open_source_text': 'SYNAPSE is an open-source project under the MIT License.',
    'suggest.title': 'Suggest New Library',
    'suggest.name': 'Library Name',
    'suggest.url': 'URL (GitHub or Docs)',
    'suggest.reason': 'Why is this library useful?',
    'suggest.submit': 'Submit Suggestion',
    'suggest.remaining': '{count} of {max} suggestions left today',
    'suggest.remaining_zero': 'Daily limit reached. Try again tomorrow.',
    'suggest.success': '🎉 Thanks for your contribution!',
    'suggest.success_detail': 'Your suggestion has been recorded and will be reviewed.',
    'suggest.error': 'Failed to submit suggestion. Please try again.',
    'settings.title': 'Settings',
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.theme_dark': 'Dark',
    'settings.theme_light': 'Light',
    'settings.theme_auto': 'Auto',
    'settings.language': 'Language',
    'settings.language_fa': 'فارسی',
    'settings.language_en': 'English',
    'settings.font_size': 'Font Size',
    'settings.font_small': 'Small',
    'settings.font_medium': 'Medium',
    'settings.font_large': 'Large',
    'settings.reduced_motion': 'Reduce motion',
    'settings.high_contrast': 'High contrast',
    'settings.search': 'Search',
    'settings.max_results': 'Max results',
    'settings.auto_suggest': 'Auto-suggest',
    'settings.chat': 'Chat',
    'settings.auto_scroll': 'Auto-scroll',
    'settings.compact_mode': 'Compact mode',
    'settings.data': 'Data',
    'settings.export_data': 'Export data',
    'settings.import_data': 'Import data',
    'settings.clear_data': 'Clear all data',
    'settings.clear_confirm': 'Are you sure you want to clear all data? This cannot be undone.',
    'settings.saved': 'Settings saved',
    'command.placeholder': 'Type a command or search...',
    'command.libraries': 'Libraries',
    'command.actions': 'Actions',
    'command.settings_cmd': 'Settings',
    'command.theme_toggle': 'Toggle Theme',
    'command.lang_toggle': 'Toggle Language',
    'command.history_open': 'History',
    'command.about_open': 'About',
    'command.suggest_lib': 'Suggest Library',
    'command.export_data': 'Export Data',
    'command.navigate': '↑↓ Navigate',
    'command.select': '↵ Select',
    'command.close': 'Esc Close',
    'tour.welcome': 'Welcome to SYNAPSE! 🎉',
    'tour.welcome_text': 'Let me give you a quick tour...',
    'tour.search': 'Search for any library right here',
    'tour.command': 'Use Cmd+K for quick access to everything',
    'tour.history': 'Your conversations are saved here',
    'tour.done': 'You\'re all set! 🚀',
    'toast.code_copied': 'Code copied!',
    'toast.link_copied': 'Link copied!',
    'toast.install_copied': 'Install command copied!',
    'toast.settings_saved': 'Settings saved.',
    'toast.export_success': 'Data exported successfully.',
    'toast.import_success': 'Data imported successfully.',
    'toast.data_cleared': 'All data cleared.',
    'toast.conversation_deleted': 'Conversation deleted.',
    'toast.error_generic': 'Something went wrong. Please try again.',
    'toast.clipboard_denied': 'Clipboard access denied. Please copy manually.',
    'error.network': '🌐 Network error. Please check your connection.',
    'error.ai_load': '🧠 AI model failed to load. Using basic search.',
    'error.data_load': '📂 Failed to load library data.',
    'error.storage_full': '💾 Storage is full. Some features are limited.',
    'error.import_invalid': '📥 Invalid import file.',
    'error.import_too_large': '📥 File size exceeds limit.',
    'error.unknown': '⚠️ Unexpected error. Please reload the page.',
    'common.ok': 'OK',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.search': 'Search...',
    'common.no_results': 'No results found',
    'common.all': 'All',
    'common.none': 'None',
    'common.optional': 'Optional',
    'common.required': 'Required',
    'shortcuts.title': 'Keyboard Shortcuts',
    'shortcuts.search': 'Quick search',
    'shortcuts.theme': 'Toggle theme',
    'shortcuts.language': 'Toggle language',
    'shortcuts.new_chat': 'New conversation',
    'shortcuts.history': 'History',
    'shortcuts.close': 'Close',
    'shortcuts.send': 'Send message',
    'shortcuts.focus_input': 'Focus input',
    'devtools.title': 'Developer Tools',
    'devtools.suggestions': 'User Suggestions',
    'devtools.no_suggestions': 'No suggestions yet.',
    'devtools.generate_issue': 'Generate GitHub Issue',
    'devtools.issue_generated': 'Issue ready. Link copied.',
    'devtools.export_suggestions': 'Export Suggestions'
  }
});

export const SYNONYMS = Object.freeze({
  'انیمیشن': ['animation', 'motion', 'animate', 'animating'],
  'متحرک': ['animation', 'motion', 'animate'],
  'حالت': ['state', 'status', 'mode'],
  'مدیریت': ['management', 'manager', 'managing'],
  'داده': ['data', 'information', 'dataset'],
  'نمودار': ['chart', 'graph', 'plot', 'diagram', 'visualization'],
  'مصورسازی': ['visualization', 'chart', 'graph'],
  'فریمورک': ['framework', 'platform'],
  'کتابخانه': ['library', 'package', 'module', 'toolkit'],
  'پکیج': ['package', 'library', 'module'],
  'ابزار': ['tool', 'utility', 'helper'],
  'رابط': ['interface', 'ui', 'frontend', 'gui'],
  'کاربری': ['ui', 'interface', 'user', 'frontend'],
  'پایگاه': ['database', 'db', 'storage', 'data'],
  'سرور': ['server', 'backend', 'api'],
  'کلاینت': ['client', 'frontend', 'browser'],
  'واکنشگرا': ['responsive', 'adaptive', 'mobile'],
  'سبک': ['lightweight', 'minimal', 'small', 'tiny'],
  'سریع': ['fast', 'quick', 'rapid', 'performance'],
  'امنیت': ['security', 'auth', 'authentication', 'protection'],
  'احراز': ['authentication', 'auth', 'login'],
  'تست': ['testing', 'test', 'unit', 'e2e'],
  'بازی': ['game', 'gaming', 'play'],
  'سهبعدی': ['3d', 'three', 'webgl', 'spatial'],
  'animation': ['انیمیشن', 'متحرک', 'حرکت'],
  'state': ['حالت', 'وضعیت'],
  'database': ['پایگاه', 'دیتابیس', 'بانک'],
  'chart': ['نمودار', 'چارت', 'گراف'],
  'lightweight': ['سبک', 'کم حجم', 'مینیمال'],
  'framework': ['فریمورک', 'چارچوب'],
  'package': ['پکیج', 'بسته', 'کتابخانه'],
  'tool': ['ابزار', 'وسیله'],
  'ui': ['رابط', 'کاربری', 'ظاهر'],
  'server': ['سرور', 'سمت سرور'],
  'client': ['کلاینت', 'سمت کاربر'],
  'security': ['امنیت', 'امنیتی'],
  'testing': ['تست', 'آزمایش', 'بررسی'],
  'game': ['بازی', 'گیم'],
  'state management': ['state management', 'state', 'مدیریت حالت'],
  'data base': ['database', 'db', 'پایگاه داده'],
  'light weight': ['lightweight', 'سبک']
});

export var STOP_WORDS = new Set([
  'و', 'با', 'برای', 'از', 'به', 'در', 'این', 'آن', 'یک', 'دو', 'سه',
  'که', 'را', 'هم', 'تا', 'یا', 'اگر', 'اما', 'چون', 'چه', 'چی',
  'است', 'هست', 'بود', 'شد', 'شود', 'کرد', 'کند',
  'من', 'تو', 'او', 'ما', 'شما', 'آنها',
  'خیلی', 'بسیار', 'کمی', 'همه', 'هر', 'چند',
  'کدام', 'چطور', 'چگونه', 'کجا', 'کی',
  'الان', 'حالا', 'بعد', 'قبل', 'هنوز',
  'بله', 'نه', 'خیر', 'آره',
  'باشه', 'خوب', 'بد', 'عالی',
  'میخوام', 'میخواهم', 'میخوای', 'دارم', 'داره',
  'لطفا', 'لطفاً', 'ممنون', 'مرسی',
  'the', 'a', 'an', 'of', 'for', 'with', 'in', 'on', 'at', 'to',
  'from', 'by', 'as', 'is', 'are', 'was', 'were', 'be', 'been',
  'i', 'you', 'he', 'she', 'it', 'we', 'they',
  'my', 'your', 'his', 'her', 'its', 'our', 'their',
  'this', 'that', 'these', 'those',
  'and', 'but', 'or', 'so', 'if', 'then', 'than',
  'very', 'much', 'many', 'some', 'any', 'all', 'each',
  'what', 'which', 'who', 'whom', 'where', 'when', 'why', 'how',
  'just', 'now', 'here', 'there', 'also', 'too',
  'can', 'will', 'would', 'could', 'should', 'may', 'might',
  'not', 'no', 'yes', 'ok', 'okay',
  'me', 'him', 'us', 'them',
  'please', 'thanks', 'thank',
  'want', 'need', 'like', 'use', 'using', 'find', 'get', 'looking',
  '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
  '۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'
]);

export var INTENT_RULES = Object.freeze([
  { intent: 'compare', patterns: [/مقایسه/i, /compare/i, /vs\b/i, /versus/i, /در مقابل/i, /تفاوت/i, /difference/i, /کدوم بهتره/i, /which (is )?better/i], weight: 10 },
  { intent: 'learn', patterns: [/یاد/i, /learn/i, /چطور/i, /how to/i, /آموزش/i, /tutorial/i, /راهنما/i, /guide/i, /شروع/i, /getting started/i, /beginner/i, /مبتدی/i], weight: 10 },
  { intent: 'clarify', patterns: [/چیست/i, /what is/i, /یعنی/i, /meaning/i, /تعریف/i, /definition/i, /مخفف/i, /abbreviation/i, /مخالف/i, /stands for/i], weight: 8 },
  { intent: 'install', patterns: [/نصب/i, /install/i, /دانلود/i, /download/i, /add/i, /get started/i, /setup/i, /راه اندازی/i], weight: 6 },
  { intent: 'greet', patterns: [/^(سلام|hi|hello|hey|درود|سلامتی|good (morning|afternoon|evening))\b/i], weight: 15 },
  { intent: 'help', patterns: [/کمک/i, /help/i, /راهنما/i, /چه کار/i, /what can you/i, /امکانات/i, /features/i], weight: 10 },
  { intent: 'search', patterns: [/.+/], weight: 1 }
]);

export var KEYBOARD = Object.freeze({
  COMMAND_PALETTE: { key: 'k', meta: true, ctrl: true, description: 'Command Palette' },
  NEW_CHAT: { key: 'n', meta: true, ctrl: true, shift: true, description: 'New conversation' },
  TOGGLE_THEME: { key: 't', meta: true, ctrl: true, shift: true, description: 'Toggle theme' },
  TOGGLE_LANGUAGE: { key: 'l', meta: true, ctrl: true, shift: true, description: 'Toggle language' },
  FOCUS_INPUT: { key: '/', description: 'Focus chat input' },
  CLOSE_MODAL: { key: 'Escape', description: 'Close modal/overlay' },
  SEARCH_INPUT: { key: 'k', meta: true, ctrl: true, description: 'Quick search' },
  GO_HISTORY: { key: 'h', meta: true, ctrl: true, description: 'Go to History' },
  GO_CHAT: { key: '1', meta: true, ctrl: true, description: 'Go to Chat' }
});

export function t(key, lang, params) {
  if (!lang) lang = 'fa';
  if (!params) params = {};
  var dict = I18N[lang] || I18N.fa;
  var text = dict[key];
  if (text === undefined) {
    var fallbackKey = key.replace('_fa', '').replace('_en', '');
    text = dict[fallbackKey];
  }
  if (text === undefined) {
    text = key;
  }
  var keys = Object.keys(params);
  for (var i = 0; i < keys.length; i++) {
    var k = keys[i];
    var v = String(params[k]);
    text = text.split('{' + k + '}').join(v);
  }
  return text;
}

export function createDefaultPreferences() {
  return {
    theme: ENV.prefersDarkMode ? 'dark' : 'light',
    language: ENV.prefersRTL ? 'fa' : 'en',
    fontSize: 'medium',
    reducedMotion: ENV.prefersReducedMotion,
    highContrast: ENV.prefersHighContrast,
    search: {
      fuzzyTolerance: 0.4,
      maxResults: 12,
      autoSuggest: true
    },
    chat: {
      showWelcomeMessage: true,
      autoScrollToBottom: true,
      compactMode: false
    },
    advanced: {
      enableVectorSearch: !ENV.isLowEndDevice,
      preloadAIModel: ENV.isHighEndDevice && !ENV.isSlowConnection,
      developerMode: false
    },
    updatedAt: new Date().toISOString()
  };
}
